version: '3'

services:
  texts_service_1:
    build: 
      context: ./texts_service_1
    ports:
      - 8000:8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_URL=${API_URL}
      - RABBIT_HOST=${RABBIT_HOST}
      - REDIS_HOST=${REDIS_HOST}

  texts_service_2:
    build: 
      context: ./texts_service_2
    ports:
      - 8002:8002
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_URL=${API_URL}
      - RABBIT_HOST=${RABBIT_HOST}
      - REDIS_HOST=${REDIS_HOST}

  generate_pic_service:
    build: 
      context: ./generate_pic_service
    restart: always
    ports:
      - 8001:8001
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBIT_HOST=${RABBIT_HOST}
      - REDIS_HOST=${REDIS_HOST}

  db:
    image: postgres
    container_name: postgres1
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - texts_service_1
      - texts_service_2

  